export const ScreenKey = {
    Home: 'Home',
    Browse: 'Browse',
    Download: 'Download',
    Search: 'Search',
    ListCourses: 'ListCourses',
    Splashscreen: 'Splashscreen',
    Login: 'Login',
    MainTab: 'MainTab',
    CourseDetail: 'CourseDetail',
    Setting: 'Setting',
    SkillDetail: 'SkillDetail',
    All: 'All',
    Courses: 'Courses',
    Paths: 'Paths',
    Authors: 'Authors',
    Profile: 'Profile',
    Register: 'Register',
    ForgetPassword: 'ForgetPassword',
    VerifyPassword: 'VerifyPassword',
    Subscription: 'Subscription',
}